name: Arduino CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git submodule update --init --recursive
      - run: docker-compose build
      - run: docker-compose run build

